/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

import javax.swing.JOptionPane;

/**
 *
 * @author Moiane Family
 */
public class Cadastrar_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_usuario
     */
    public Cadastrar_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel_nomUsuario = new javax.swing.JLabel();
        jTextField_nomUsuario = new javax.swing.JTextField();
        jLabel_senha = new javax.swing.JLabel();
        jLabel_confirmarSenha = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jTextField_senha = new javax.swing.JTextField();
        jTextField_confirmarSenha = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jLabel_codConfirmarUsuario = new javax.swing.JLabel();
        jTextField_codConfirmarUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_cod = new javax.swing.JTextField();
        jLabel_Cod = new javax.swing.JLabel();
        jButton_voltar = new javax.swing.JButton();
        jButton_avancar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cadastro de Novo Utilizador");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 0, 210, 30);

        jLabel_nomUsuario.setText("Nome de Usuario");
        getContentPane().add(jLabel_nomUsuario);
        jLabel_nomUsuario.setBounds(50, 50, 90, 20);

        jTextField_nomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nomUsuario);
        jTextField_nomUsuario.setBounds(180, 50, 170, 20);

        jLabel_senha.setText("Definir Senha");
        getContentPane().add(jLabel_senha);
        jLabel_senha.setBounds(50, 90, 100, 20);

        jLabel_confirmarSenha.setText("Confirmar Senha ");
        getContentPane().add(jLabel_confirmarSenha);
        jLabel_confirmarSenha.setBounds(50, 130, 90, 20);

        jLabel_email.setText("Email do usuario");
        getContentPane().add(jLabel_email);
        jLabel_email.setBounds(50, 170, 90, 20);

        jTextField_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_senha);
        jTextField_senha.setBounds(160, 90, 160, 20);

        jTextField_confirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_confirmarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_confirmarSenha);
        jTextField_confirmarSenha.setBounds(160, 130, 130, 20);

        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_email);
        jTextField_email.setBounds(160, 170, 130, 20);

        jLabel_codConfirmarUsuario.setText("Codigo de Confirmacao ");
        getContentPane().add(jLabel_codConfirmarUsuario);
        jLabel_codConfirmarUsuario.setBounds(50, 210, 120, 20);
        getContentPane().add(jTextField_codConfirmarUsuario);
        jTextField_codConfirmarUsuario.setBounds(180, 210, 130, 20);

        jLabel7.setText("Sera enviado um codigo para o email da Instituicao ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 250, 260, 20);

        jTextField_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_cod);
        jTextField_cod.setBounds(160, 310, 110, 20);

        jLabel_Cod.setText("Insira o codigo");
        getContentPane().add(jLabel_Cod);
        jLabel_Cod.setBounds(40, 310, 100, 20);

        jButton_voltar.setText("Voltar");
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(30, 350, 61, 23);

        jButton_avancar.setText("Avancar");
        jButton_avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avancarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_avancar);
        jButton_avancar.setBounds(420, 350, 73, 23);

        jLabel1.setText("Para ter acesso, ao codigo, aproxime a Secretaria");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 280, 250, 20);

        setSize(new java.awt.Dimension(535, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomUsuarioActionPerformed

    private void jTextField_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_senhaActionPerformed

    private void jTextField_confirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_confirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_confirmarSenhaActionPerformed

    private void jTextField_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        // TODO add your handling code here:
        Login login =new Login();
        login.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avancarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, " Cadastrado com Sucesso");
        Login login = new Login();
           login.setVisible(true);
           
           dispose();
    }//GEN-LAST:event_jButton_avancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_avancar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Cod;
    private javax.swing.JLabel jLabel_codConfirmarUsuario;
    private javax.swing.JLabel jLabel_confirmarSenha;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nomUsuario;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JTextField jTextField_cod;
    private javax.swing.JTextField jTextField_codConfirmarUsuario;
    private javax.swing.JTextField jTextField_confirmarSenha;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nomUsuario;
    private javax.swing.JTextField jTextField_senha;
    // End of variables declaration//GEN-END:variables
}
