/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
import java.sql.*;
/**
 *
 * @author Moiane Family
 */
public class Certificacao extends javax.swing.JFrame {

    /**
     * Creates new form Certificacao
     */
    public Certificacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_numProcesso = new javax.swing.JTextField();
        jTextField_nomeReq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_requer = new javax.swing.JTextField();
        jButton_Anexar = new javax.swing.JButton();
        jButton_Verificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField_form = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField_certifi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField_bi = new javax.swing.JTextField();
        jButton_gravar = new javax.swing.JButton();
        jButton_limpar = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_genero = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_processo = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Novo Processo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 250, 40);

        jLabel2.setText("Numero do Processo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 30, 98, 14);

        jLabel3.setText("Nome do Requerente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 102, 14);

        jTextField_numProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numProcessoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_numProcesso);
        jTextField_numProcesso.setBounds(600, 30, 130, 30);
        getContentPane().add(jTextField_nomeReq);
        jTextField_nomeReq.setBounds(140, 80, 200, 20);

        jLabel4.setText("Requerimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 90, 20);
        getContentPane().add(jTextField_requer);
        jTextField_requer.setBounds(20, 230, 250, 30);

        jButton_Anexar.setText("Anexar");
        jButton_Anexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnexarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Anexar);
        jButton_Anexar.setBounds(20, 190, 100, 30);

        jButton_Verificar.setText("Verificar");
        jButton_Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Verificar);
        jButton_Verificar.setBounds(140, 190, 120, 30);

        jLabel5.setText("Formulario Preenchido ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 280, 130, 20);

        jButton1.setText("Anexar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 320, 100, 30);

        jButton2.setText("Verificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 320, 120, 30);
        getContentPane().add(jTextField_form);
        jTextField_form.setBounds(20, 360, 250, 30);

        jLabel6.setText("Certificados");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 420, 100, 20);

        jLabel7.setText("NOTA: Adicione 1 unico PDF, com todo os certificados necessarios");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 450, 320, 30);

        jButton3.setText("Anexar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 490, 90, 30);

        jButton4.setText("Verificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 490, 130, 30);

        jTextField_certifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_certifiActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_certifi);
        jTextField_certifi.setBounds(20, 530, 270, 30);

        jLabel8.setText("Fotocopia do B.I autenticada");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 240, 160, 30);

        jButton5.setText("Anexar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(440, 270, 100, 30);

        jButton6.setText("Verificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(550, 270, 130, 30);
        getContentPane().add(jTextField_bi);
        jTextField_bi.setBounds(430, 310, 250, 30);

        jButton_gravar.setText("Gravar");
        jButton_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gravarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_gravar);
        jButton_gravar.setBounds(160, 610, 80, 30);

        jButton_limpar.setText("Limpar campos");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_limpar);
        jButton_limpar.setBounds(10, 610, 120, 30);

        jButton_sair.setText("sair");
        getContentPane().add(jButton_sair);
        jButton_sair.setBounds(690, 640, 49, 30);

        jLabel9.setText("Genero");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 140, 60, 20);

        jComboBox_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero", "Feminino", "Masculino" }));
        getContentPane().add(jComboBox_genero);
        jComboBox_genero.setBounds(580, 140, 70, 20);

        jLabel10.setText("Tipo de Processo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 120, 100, 20);

        jComboBox_processo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Certificacao", "Equivalencia" }));
        getContentPane().add(jComboBox_processo);
        jComboBox_processo.setBounds(130, 120, 130, 20);

        jButton7.setText("Voltar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(570, 640, 90, 30);

        setBounds(0, 0, 771, 743);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_numProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numProcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numProcessoActionPerformed

    private void jButton_AnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnexarActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField_requer.setText(filename);
        
    }//GEN-LAST:event_jButton_AnexarActionPerformed

    private void jButton_VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerificarActionPerformed
        // TODO add your handling code here:
        try{
        
         File f = new File(jTextField_requer.getText());
         if(f.exists()){
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(f);
            }else{
                JOptionPane.showMessageDialog(this,"Ficheiro nao suportado");
            }
         }else{
            JOptionPane.showMessageDialog(this,"Ficheiro nao encontrado"); 
         }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_VerificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField_form.setText(filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        
         File f = new File(jTextField_form.getText());
         if(f.exists()){
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(f);
            }else{
                JOptionPane.showMessageDialog(this,"Ficheiro nao suportado");
            }
         }else{
            JOptionPane.showMessageDialog(this,"Ficheiro nao encontrado"); 
         }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField_certifi.setText(filename);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        
         File f = new File(jTextField_certifi.getText());
         if(f.exists()){
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(f);
            }else{
                JOptionPane.showMessageDialog(this,"Ficheiro nao suportado");
            }
         }else{
            JOptionPane.showMessageDialog(this,"Ficheiro nao encontrado"); 
         }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_certifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_certifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_certifiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField_bi.setText(filename);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        
         File f = new File(jTextField_bi.getText());
         if(f.exists()){
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(f);
            }else{
                JOptionPane.showMessageDialog(this,"Ficheiro nao suportado");
            }
         }else{
            JOptionPane.showMessageDialog(this,"Ficheiro nao encontrado"); 
         }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gravarActionPerformed
        // TODO add your handling code here:
        String Nome=jTextField_nomeReq.getText();
        String Processo=(String)jComboBox_processo.getSelectedItem();
        String NumProcesso=jTextField_numProcesso.getText();
        String Requerimento=jTextField_requer.getText();
        String Formulario=jTextField_form.getText();
        String Certificado=jTextField_certifi.getText();
        String Fotocopia= jTextField_bi.getText();
        String Genero=(String)jComboBox_genero.getSelectedItem();
        
        try{
            Connection con= ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into Processos values('"+Nome+"','"+Processo+"','"+NumProcesso+"','"+Requerimento+"','"+Formulario+"','"+Certificado+"','"+Fotocopia+"','"+Genero+"')");
            JOptionPane.showMessageDialog(null,"Processo Gravado com sucesso");
            setVisible(false);
            new Certificacao().setVisible(true);
        }catch(Exception e){}
            JOptionPane.showMessageDialog(null,"Numero de Proceeso ja existente");
    }//GEN-LAST:event_jButton_gravarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Tela_Principal principal = new Tela_Principal();
           principal.setVisible(true);
           
           dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        // TODO add your handling code here:
        new Certificacao().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Certificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_Anexar;
    private javax.swing.JButton jButton_Verificar;
    private javax.swing.JButton jButton_gravar;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JComboBox<String> jComboBox_genero;
    private javax.swing.JComboBox<String> jComboBox_processo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_bi;
    private javax.swing.JTextField jTextField_certifi;
    private javax.swing.JTextField jTextField_form;
    private javax.swing.JTextField jTextField_nomeReq;
    private javax.swing.JTextField jTextField_numProcesso;
    private javax.swing.JTextField jTextField_requer;
    // End of variables declaration//GEN-END:variables
}
