/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

import javax.swing.JOptionPane;

/**
 *
 * @author Moiane Family
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_utilizador = new javax.swing.JLabel();
        jTextField_utilizador = new javax.swing.JTextField();
        jLabel_senha = new javax.swing.JLabel();
        jPasswordField_senha = new javax.swing.JPasswordField();
        jButton_castranovo = new javax.swing.JButton();
        jButton_entrar = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 280, 170);

        jLabel_utilizador.setText("Utilizador:");
        getContentPane().add(jLabel_utilizador);
        jLabel_utilizador.setBounds(100, 230, 70, 30);

        jTextField_utilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_utilizadorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_utilizador);
        jTextField_utilizador.setBounds(180, 230, 160, 30);

        jLabel_senha.setText("Senha");
        getContentPane().add(jLabel_senha);
        jLabel_senha.setBounds(100, 270, 50, 30);

        jPasswordField_senha.setText("ield1");
        jPasswordField_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_senha);
        jPasswordField_senha.setBounds(180, 270, 160, 30);

        jButton_castranovo.setText("Cadastrar novo Usuario");
        jButton_castranovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_castranovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_castranovo);
        jButton_castranovo.setBounds(20, 350, 150, 20);

        jButton_entrar.setText("Entrar");
        jButton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_entrar);
        jButton_entrar.setBounds(370, 350, 63, 23);

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_sair);
        jButton_sair.setBounds(450, 350, 51, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 190, 70, 20);

        jCheckBox1.setText("Mostrar senha");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(180, 310, 100, 20);

        setSize(new java.awt.Dimension(522, 391));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_utilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_utilizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_utilizadorActionPerformed

    private void jPasswordField_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_senhaActionPerformed

    private void jButton_castranovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_castranovoActionPerformed
           // TODO add your handling code here:
           Cadastrar_usuario cadastrar = new Cadastrar_usuario();
           cadastrar.setVisible(true);
           
           dispose();
    }//GEN-LAST:event_jButton_castranovoActionPerformed

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Deseja sair da Aplicacao?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
           System.exit(0); 
        }
        
    }//GEN-LAST:event_jButton_sairActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
           // jPasswordField1.setEcoChar(char()0);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entrarActionPerformed
        // TODO add your handling code here:
        Tela_Principal principal = new Tela_Principal();
           principal.setVisible(true);
           
           dispose();
    }//GEN-LAST:event_jButton_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_castranovo;
    private javax.swing.JButton jButton_entrar;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JLabel jLabel_utilizador;
    private javax.swing.JPasswordField jPasswordField_senha;
    private javax.swing.JTextField jTextField_utilizador;
    // End of variables declaration//GEN-END:variables
}
