/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

/**
 *
 * @author Moiane Family
 */
public class PesquisarProcessos extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarProcessos
     */
    public PesquisarProcessos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_NumProcesso = new javax.swing.JLabel();
        jTextField_NumProcesso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar Processos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 230, 60);

        jLabel_NumProcesso.setText("Numero do Processo:");
        getContentPane().add(jLabel_NumProcesso);
        jLabel_NumProcesso.setBounds(20, 70, 120, 20);

        jTextField_NumProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumProcessoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_NumProcesso);
        jTextField_NumProcesso.setBounds(130, 70, 150, 20);

        jLabel2.setText("Nome do Requerente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 110, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 110, 260, 20);

        jButton1.setText("Procurar");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 160, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NumProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumProcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumProcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarProcessos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_NumProcesso;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_NumProcesso;
    // End of variables declaration//GEN-END:variables
}
