/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodos;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import Project.ConnectionProvider;

/**
 *
 * @author Moiane Family
 */
public class RemoverProcessos extends javax.swing.JFrame {

    /**
     * Creates new form RemoverProcessos
     */
    public RemoverProcessos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField_numProc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nomReq = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_processo = new javax.swing.JTextField();
        jTextField_numProcesso = new javax.swing.JTextField();
        jTextField_requer = new javax.swing.JTextField();
        jTextField_form = new javax.swing.JTextField();
        jTextField_certifi = new javax.swing.JTextField();
        jTextField_bi = new javax.swing.JTextField();
        jTextFieldgenero = new javax.swing.JTextField();
        jButton_actualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setText("Numero do Processo ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 110, 20);

        jTextField_numProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numProcActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_numProc);
        jTextField_numProc.setBounds(140, 80, 160, 20);

        jLabel3.setText("Nome do requerente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 110, 20);
        getContentPane().add(jTextField_nomReq);
        jTextField_nomReq.setBounds(140, 160, 170, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 130, 620, 10);

        jLabel4.setText("Processo ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 70, 20);

        jLabel5.setText("NumProcesso");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 70, 20);

        jLabel6.setText("Requerimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 250, 70, 20);

        jLabel7.setText("Formulario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 50, 14);

        jLabel8.setText("Certificado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 310, 60, 20);

        jLabel9.setText("Fotocopia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 340, 60, 20);

        jLabel10.setText("Genero");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 370, 50, 20);

        jTextField_processo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_processoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_processo);
        jTextField_processo.setBounds(80, 190, 200, 20);
        getContentPane().add(jTextField_numProcesso);
        jTextField_numProcesso.setBounds(90, 220, 180, 20);
        getContentPane().add(jTextField_requer);
        jTextField_requer.setBounds(90, 250, 290, 20);
        getContentPane().add(jTextField_form);
        jTextField_form.setBounds(70, 280, 330, 20);
        getContentPane().add(jTextField_certifi);
        jTextField_certifi.setBounds(70, 310, 300, 20);
        getContentPane().add(jTextField_bi);
        jTextField_bi.setBounds(70, 340, 290, 20);
        getContentPane().add(jTextFieldgenero);
        jTextFieldgenero.setBounds(50, 370, 120, 20);

        jButton_actualizar.setText("Apagar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizar);
        jButton_actualizar.setBounds(110, 430, 80, 23);

        jButton2.setText("sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 430, 90, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Remover Processos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 200, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_numProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numProcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numProcActionPerformed

    private void jTextField_processoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_processoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_processoActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        String numprocesso1=jTextField_numProc.getText();
        String Nome=jTextField_nomReq.getText();
        String Processo=jTextField_processo.getText();
        String NumProcesso=jTextField_numProcesso.getText();
        String Requerimento=jTextField_requer.getText();
        String Formulario=jTextField_form.getText();
        String Certificado=jTextField_certifi.getText();
        String Fotocopia=jTextField_bi.getText();
        String Genero=jTextFieldgenero.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update Processos Nome='"+Nome+"',Processo='"+Processo+"',NumProcesso='"+NumProcesso+"',Requerimento='"+Requerimento+"',Formulario='"+Formulario+"',Certificado='"+Certificado+"',Fotocopia='"+Fotocopia+"',Genero='"+Genero+"'");
            JOptionPane.showMessageDialog(null,"Processo Apagado");
            setVisible(false);
            new Actualizar().setVisible(true);
            dispose();

        }catch(Exception e){}
            JOptionPane.showMessageDialog(null,"Processo nao encontrado");
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tela_Principal principal=new Tela_Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverProcessos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_bi;
    private javax.swing.JTextField jTextField_certifi;
    private javax.swing.JTextField jTextField_form;
    private javax.swing.JTextField jTextField_nomReq;
    private javax.swing.JTextField jTextField_numProc;
    private javax.swing.JTextField jTextField_numProcesso;
    private javax.swing.JTextField jTextField_processo;
    private javax.swing.JTextField jTextField_requer;
    private javax.swing.JTextField jTextFieldgenero;
    // End of variables declaration//GEN-END:variables
}
